collections:
  authors:
    output: true
  projects:
    output: true
  products:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
    load_paths:
        - _sass
        -  /Users/featherlite569/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootstrap-4.3.1/assets/stylesheets

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag